### ISSUE TITLE
Glue Data Catalog Database State Change Possible Values Wrong

### ISSUE THREAD

**Issue by cbts-alec-johnson** [awsdocs/amazon-cloudwatch-events-user-guide#18]
The possible values for Glue Data Catalog Database State Change are wrong in the docs. 

[The docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html#glue-event-types) list only CreateTable, UpdateTable, and CreateDatabase as possible values. 
![image](https://user-images.githubusercontent.com/57811015/178775938-9a0b21a6-41ba-4289-a8e5-d5ade5908800.png)

The actual possible values, according to [these docs](https://docs.aws.amazon.com/glue/latest/dg/automating-awsglue-with-cloudwatch-events.html), are CreateDatabase, DeleteDatabase, CreateTable, DeleteTable and BatchDeleteTable. UpdateTable is not a possible value.
![image](https://user-images.githubusercontent.com/57811015/178776704-8c9a3d59-7ce9-4ea3-acdd-4273f9a08d43.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
