### ISSUE TITLE
Invalid cron job syntax?

### ISSUE THREAD

**Issue by brysontyrrell** [awsdocs/amazon-cloudwatch-events-user-guide#2]
In the docs for Scheduled Events, accepted values for "Day-of-week" include `*` but trying to use that for scheduled Lambdas results in an error in CloudFormation stating the syntax is invalid.

Is this accurate?

https://github.com/awsdocs/amazon-cloudwatch-events-user-guide/blob/master/doc_source/ScheduledEvents.md

**Comment by chrisdr** [comment]
I'm guessing you missed noticing the first bullet under **Limits**.  Let me know whether this is the case:

You can't specify the Day-of-month and Day-of-week fields in the same cron expression. If you specify a value (or a *) in one of the fields, you must use a ? (question mark) in the other.

**Comment by brysontyrrell** [comment]
I did miss that. My apologies! Closing.

**Comment by chrisdr** [comment]
Not a problem!  This is a fairly common mistake, I will look at trying to make that more noticeable.
