### ISSUE TITLE
Document that Lambda should exit with success ?

### ISSUE THREAD

**Issue by wolruf** [awsdocs/amazon-cloudwatch-events-user-guide#5]
If Cloudwatch Event triggers a Lambda which doesn't exit with success, Cloudwatch Event will trigger it again. Could be worth documenting if verified.

**Comment by chrisdr** [comment]
I checked with the team and that is not the actual behavior. CloudWatch Events triggers Lambda asynchronously, and does not know whether the Lambda execution was or was not successful. I don't know what might have caused the behavior you were seeing.

**Comment by wolruf** [comment]
Sorry for the noise then, I'll follow-up with the support ticket owner.
