### ISSUE TITLE
Description does not match examples

### ISSUE THREAD

**Issue by michael-k** [awsdocs/amazon-cloudwatch-events-user-guide#6]
The description of the examples at the bottom of https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#RateExpressions talks about 3 examples, but 4 are shown.

The code in the repo (last touched 3 months ago) does not have this problem (only 3 examples): https://github.com/awsdocs/amazon-cloudwatch-events-user-guide/blob/master/doc_source/ScheduledEvents.md#rate-expressions

**Comment by vatshat** [comment]
Can the documentation for CWE --> SSM please be updated to include/explain that parameters in SSM automation documents should be in arrays. The current docs only provide an example of constants and API docs, don't help either. 
https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_InputTransformer.html

For example the "AWS-EnableS3BucketEncryption" I've got it as follows in order for it to work:

~$ aws events list-targets-by-rule --rule ssm-testing
{
	"Targets": [
        {
			"RoleArn": "arn:aws:iam::12345678910:role/service-role/AWS_Events_Invoke_Start_Automation_Execution_338634571",
			"Id": "Id543190923011810",
			"Arn": "arn:aws:ssm:eu-west-1::automation-definition/AWS-EnableS3BucketEncryption:$DEFAULT",
			"InputTransformer": {
				"InputPathsMap": {
					"BucketName": "$.detail.resourceId"
				},
				"InputTemplate": {
					"AutomationAssumeRole": ["arn:aws:iam::12345678910:role/AWS_SSMAutomationServiceRole"],
					"BucketName": [<BucketName>],
					"SSEAlgorithm": ["AES256"]
				}
			}
		}
	]
}

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
